name: AI Push Review

on:
  push:
    branches:
      - "**"

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate AI Review
        id: review
        run: |
          DIFF=$(git show -U0 HEAD)
          echo "Reviewing diff with OpenAI..."
          REVIEW=$(echo "$DIFF" | \
            openai api chat.completions.create \
              -m gpt-5-mini \
              -g user \
              -c "You are acting as a research paper assistant reviewing this push. Provide constructive, detailed feedback in the style of an academic peer review.")
          echo "$REVIEW" > review.md

      - name: Create GitHub Issue with AI Suggestions
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "AI Review Suggestions for push ${{ github.sha }}"
          content-filepath: review.md
          labels: ai-review, research-paper
