# .github/workflows/ai-push-review.yml
name: AI Push Review

on:
  push:
    branches:
      - "**"   # run on every push to any branch

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write   # needed to create issues

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate AI Suggestions
        id: ai
        uses: sshnaidm/gpt-code-review-action@v3.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            You are acting as a research paper assistant reviewing this push.
            Provide constructive, detailed feedback in the style of an academic peer review.

            Focus on:
            - Clarity of explanations and naming
            - Reproducibility of experiments/configs
            - Scientific rigor of assumptions
            - Readability and structure like publishable pseudocode
            - Missing references, comments, or tests

      - name: Create GitHub Issue with Suggestions
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "AI Review Suggestions for push ${{ github.sha }}"
          content-filepath: ${{ steps.ai.outputs.review_file }}
          labels: ai-review, research-paper
