name: AI Push Review

on:
  push:
    branches:
      - "**"

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install OpenAI SDK
        run: pip install openai==1.79.0

      - name: Generate AI Review
        run: |
          python - <<'EOF'
          import subprocess, openai, os

          diff = subprocess.check_output(["git", "show", "-U0", "HEAD"], text=True)
          client = openai.OpenAI(
              api_key=os.environ["OPENAI_API_KEY"],
              project=os.environ["OPENAI_PROJECT"]
          )
          resp = client.chat.completions.create(
              model="gpt-4o-mini",
              messages=[
                  {"role": "system", "content": "You are a research paper assistant reviewing code pushes."},
                  {"role": "user", "content": f"Review this code diff as if preparing it for a research paper:\n\n{diff}"}
              ]
          )
          review = resp.choices[0].message.content
          with open("review.md", "w", encoding="utf-8") as f:
              f.write(review)
          EOF
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}

      - name: Create GitHub Issue with AI Suggestions
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "AI Review Suggestions for push ${{ github.sha }}"
          content-filepath: review.md
          labels: ai-review, research-paper
