name: AI Push Review

on:
  workflow_dispatch:

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install OpenAI SDK
        run: pip install openai==1.79.0

      - name: Generate AI Review (via OpenRouter)
        run: |
          python - <<'EOF'
          import subprocess, openai, os

          diff = subprocess.check_output(["git", "show", "-U0", "HEAD"], text=True)

          # Configure OpenRouter as the base URL
          client = openai.OpenAI(
              base_url="https://openrouter.ai/api/v1",
              api_key=os.environ["OPENROUTER_API_KEY"]
          )

          resp = client.chat.completions.create(
              model="openai/gpt-5-mini",
              messages=[
                  {"role": "system", "content": "You are a senior ML paper reviewer. Be brief, judgmental on the big picture, and propose concrete remedies. Avoid code nitpicks unless they break results."},
                  {"role": "user", "content": f"Given this git diff, produce a VERY CONCISE, HOLISTIC REVIEW (bullet points). Do NOT restate changes. Judge the overall approach: objectives/scope, dataset quality/splits/leakage, tokenizer/model alignment, training regime (loss, schedule, regularization), evaluation design (benchmarks, baselines, ablations, seeds, confidence), reproducibility (versions, scripts), safety/compliance (PII/licensing). For esach issue, give a concrete fix. End with a 3–5 item ‘Next steps’ checklist focusing on experiments or documentation to add.\n\nDiff:\n\n{diff}"}
              ]
          )

          review = resp.choices[0].message.content
          with open("review.md", "w", encoding="utf-8") as f:
              f.write(review)
          EOF
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Create GitHub Issue with AI Suggestions
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "AI Review Suggestions for push ${{ github.sha }}"
          content-filepath: review.md
          labels: ai-review, research-paper
